[package]
name = "kirily-wasm"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kirily-image.workspace = true
kirily-mask.workspace = true
kirily-raster.workspace = true
wasm-bindgen.workspace = true
console_error_panic_hook.workspace = true

[lints]
workspace = true
